### ISSUE TITLE
Failed to get world settings

### ISSUE THREAD

**Issue by nzAily** [HiveGamesOSS/Chunker#130]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

Bedrock 1.21.40

### Output World Version

1.21.40

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `A fatal error occurred during conversion.`
Stack Trace: 
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "com.hivemc.chunker.nbt.tags.collection.CompoundTag.getString(String, String)" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.Environment.cancel(Environment.java:85)
	at com.hivemc.chunker.conversion.WorldConverter.cancel(WorldConverter.java:609)
	at com.hivemc.chunker.conversion.WorldConverter.logFatalException(WorldConverter.java:441)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.handleException(TaskExecutor.java:109)
	at com.hivemc.chunker.scheduling.task.WrappedTask.lambda$setupFuture$0(WrappedTask.java:57)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:44)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "com.hivemc.chunker.nbt.tags.collection.CompoundTag.getString(String, String)" is null
	at com.hivemc.chunker.conversion.encoding.bedrock.base.reader.BedrockLevelReader.readCustomLevelSetting(BedrockLevelReader.java:296)
	at com.hivemc.chunker.conversion.encoding.bedrock.v1_17.reader.LevelReader.readCustomLevelSetting(LevelReader.java:33)
	at com.hivemc.chunker.conversion.encoding.bedrock.v1_18.reader.LevelReader.readCustomLevelSetting(LevelReader.java:25)
	at com.hivemc.chunker.conversion.encoding.bedrock.v1_19.reader.LevelReader.readCustomLevelSetting(LevelReader.java:33)
	at com.hivemc.chunker.conversion.encoding.bedrock.v1_20.reader.LevelReader.readCustomLevelSetting(LevelReader.java:25)
	at com.hivemc.chunker.conversion.encoding.bedrock.v1_20_50.reader.LevelReader.readCustomLevelSetting(LevelReader.java:34)
	at com.hivemc.chunker.conversion.encoding.bedrock.v1_21.reader.LevelReader.readCustomLevelSetting(LevelReader.java:25)
	at com.hivemc.chunker.conversion.intermediate.level.ChunkerLevelSettings.fromNBT(ChunkerLevelSettings.java:531)
	at com.hivemc.chunker.conversion.encoding.bedrock.base.reader.BedrockLevelReader.parseLevelSettings(BedrockLevelReader.java:244)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:20)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:8)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	... 2 more
```

**Comment by FormallyMyles** [comment]
If you're able to send the level.dat file from your world so we can look at what Chunker fails to load, it would be appreciated. You can send it here or email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
Thanks, we'll get this fixed for the next release :)

**Comment by nzAily** [comment]
> Thanks, we'll get this fixed for the next release :)

Hope you can fix it, and thank you :)

**Comment by FormallyMyles** [comment]
This should be fixed in the latest release - https://github.com/HiveGamesOSS/Chunker/releases
