### ISSUE TITLE
04520a0a-2db9-4cb9-a475-891caee64933

### ISSUE THREAD

**Issue by kizutori** [HiveGamesOSS/Chunker#137]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

Java 1.20.1

### Output World Version

Bedrock 1.21.40

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `A fatal error occurred during conversion.`
Stack Trace: 
```
java.util.concurrent.CompletionException: java.util.zip.ZipException: incorrect data check
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.Environment.cancel(Environment.java:85)
	at com.hivemc.chunker.conversion.WorldConverter.cancel(WorldConverter.java:609)
	at com.hivemc.chunker.conversion.WorldConverter.logFatalException(WorldConverter.java:441)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.handleException(TaskExecutor.java:109)
	at com.hivemc.chunker.scheduling.task.WrappedTask.lambda$setupFuture$0(WrappedTask.java:57)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:44)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.zip.ZipException: incorrect data check
	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/java.io.DataInputStream.readUnsignedByte(Unknown Source)
	at com.hivemc.chunker.nbt.io.DataInputReaderBE.readUnsignedByte(DataInputReaderBE.java:35)
	at com.hivemc.chunker.nbt.tags.Tag.decodeTagClass(Tag.java:633)
	at com.hivemc.chunker.nbt.tags.Tag.decodeNamed(Tag.java:562)
	at com.hivemc.chunker.nbt.tags.Tag.readZLibJavaNBT(Tag.java:483)
	at com.hivemc.chunker.conversion.encoding.java.base.reader.util.MCAReader.decompressColumn(MCAReader.java:114)
	at com.hivemc.chunker.conversion.encoding.java.base.reader.util.MCAReader.lambda$readColumn$0(MCAReader.java:97)
	at com.hivemc.chunker.scheduling.function.ThrowableSupplier.invoke(ThrowableSupplier.java:20)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	... 2 more
```

**Comment by FormallyMyles** [comment]
Your world likely has corrupted chunks and Chunker isn't able to convert it.

**Comment by FormallyMyles** [comment]
Your world likely has corrupted chunks and Chunker isn't able to convert it.
