### ISSUE TITLE
Conversion bug attempting to convert 1.21.3 world

### ISSUE THREAD

**Issue by Owls-Parliament** [HiveGamesOSS/Chunker#138]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

1.21.3

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Displayed: `The backend process was killed unexpectedly.`
Crashed before I could even select the desired world version into which to convert

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
I looked through your logs and seeing this:
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no awt in system library path: C:\Users\XXXX\AppData\Local\Temp\XXXX\resources\chunker-cli\runtime\bin [in thread "Task Processor 0"]
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at java.desktop/java.awt.image.ColorModel$1.run(Unknown Source)
	at java.desktop/java.awt.image.ColorModel$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.image.ColorModel.loadLibraries(Unknown Source)
	at java.desktop/java.awt.image.ColorModel.<clinit>(Unknown Source)
	at java.desktop/java.awt.image.BufferedImage.<clinit>(Unknown Source)
	... 9 more
```

It seems like maybe Chunker didn't extract properly when you ran the exe, have you tried closing & reopening it? Alternatively you can try the windows .zip version from the releases page.
I unfortunately otherwise can't see anything obvious, have you tried other worlds?

**Comment by Owls-Parliament** [comment]
Closing and reopening did allow me to extract correctly. Thank you.
