### ISSUE TITLE
this keeps happening

### ISSUE THREAD

**Issue by Faithful927** [HiveGamesOSS/Chunker#151]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

N/A

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `The backend process was killed unexpectedly.`

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)

**Comment by Faithful927** [comment]
[main.log](https://github.com/user-attachments/files/17902522/main.log)

**Comment by FormallyMyles** [comment]
Have you tried closing all instances of Chunker and reopening it? Seems like it fails to load some java.security file which may have not extracted properly.

**Comment by Faithful927** [comment]
Ive done that and ive redownloaded

**Comment by FormallyMyles** [comment]
Seems odd, ensure you're only opening it once (it can take a while to extract all the data) while it opens. You can also try the .zip version (note: it isn't currently signed like the exe so Windows may have a SmartScreen warning) - https://github.com/HiveGamesOSS/Chunker/releases/download/1.4.0/Chunker-1.4.0-windows-x86.zip

**Comment by Faithful927** [comment]
Error Displayed: `A fatal error occurred during conversion.`
Stack Trace: 
```
java.util.concurrent.CompletionException: org.iq80.leveldb.impl.DbImpl$BackgroundProcessingException: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.Environment.cancel(Environment.java:85)
	at com.hivemc.chunker.conversion.WorldConverter.cancel(WorldConverter.java:609)
	at com.hivemc.chunker.conversion.WorldConverter.logFatalException(WorldConverter.java:441)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.handleException(TaskExecutor.java:109)
	at com.hivemc.chunker.scheduling.task.WrappedTask.lambda$setupFuture$0(WrappedTask.java:57)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:44)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.iq80.leveldb.impl.DbImpl$BackgroundProcessingException: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
	at org.iq80.leveldb.impl.DbImpl.checkBackgroundException(DbImpl.java:550)
	at org.iq80.leveldb.impl.DbImpl.writeInternal(DbImpl.java:952)
	at org.iq80.leveldb.impl.DbImpl.put(DbImpl.java:875)
	at org.iq80.leveldb.impl.DbImpl.put(DbImpl.java:867)
	at com.hivemc.chunker.conversion.encoding.bedrock.v1_18_30.writer.ColumnWriter.writeEntities(ColumnWriter.java:64)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:20)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:8)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	... 2 more
Caused by: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
	at java.base/sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.truncate(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.truncate(Unknown Source)
	at org.iq80.leveldb.fileenv.MMWritableFile.close(MMWritableFile.java:114)
	at org.iq80.leveldb.fileenv.EnvImpl$DelegateWritableFile.close(EnvImpl.java:215)
	at org.iq80.leveldb.impl.DbImpl.buildTable(DbImpl.java:1352)
	at org.iq80.leveldb.impl.DbImpl.writeLevel0Table(DbImpl.java:1303)
	at org.iq80.leveldb.impl.DbImpl.compactMemTable(DbImpl.java:1263)
	at org.iq80.leveldb.impl.DbImpl.backgroundCompaction(DbImpl.java:593)
	at org.iq80.leveldb.impl.DbImpl.backgroundCall(DbImpl.java:562)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
```

**Comment by Faithful927** [comment]
i downloaded it and tried it but then it gave me this

**Comment by FormallyMyles** [comment]
Would you be able to provide the following:
- What version / format is the world you're trying to convert? (e.g. Bedrock 1.20.40)
- What version / format are you trying to convert to? (e.g. Java 1.20.4)
- How much free hard drive space do you have?
- Do you know how much RAM / what CPU your PC has?

**Comment by Faithful927** [comment]
latest version on java to 1.21.40 bedrock
over 7 gb
and 64 ram on an i5

**Comment by FormallyMyles** [comment]
> latest version on java to 1.21.40 bedrock over 7 gb and 64 ram on an i5

If you're able to send the world to `chunker-public@hivemc.com` we can try to see if we can replicate it, otherwise it's a bit of an odd error that I've personally not seen before.

**Comment by Faithful927** [comment]
im a little confused where to go? i followed to chunker-public@hivemc.com but im confused on where to go from there

**Comment by Faithful927** [comment]
its sending me to the main page of the hive

**Comment by FormallyMyles** [comment]
Closing as I haven't heard back from you, let us know more details and we can try to look further.
