### ISSUE TITLE
world conversion issue

### ISSUE THREAD

**Issue by chexmicals** [HiveGamesOSS/Chunker#159]
### Chunker Version

8f927d10-7556-4e0a-aa7c-10f457726c33

### Input World Version

Bedrock 1.21.20

### Output World Version

Java 1.21.3

### Platform / Operating System

win32-x64-10.0.26100

### Issue Description

Error Displayed: `A fatal error occurred during conversion.`
Stack Trace: 
```
java.util.concurrent.CompletionException: com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.Environment.cancel(Environment.java:85)
	at com.hivemc.chunker.conversion.WorldConverter.cancel(WorldConverter.java:609)
	at com.hivemc.chunker.conversion.WorldConverter.logFatalException(WorldConverter.java:441)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.handleException(TaskExecutor.java:109)
	at com.hivemc.chunker.scheduling.task.WrappedTask.lambda$setupFuture$0(WrappedTask.java:57)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:44)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: Java heap space
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2083)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4898)
	at org.iq80.leveldb.util.LRUCache.load(LRUCache.java:56)
	at org.iq80.leveldb.table.Table.readBlock(Table.java:164)
	at org.iq80.leveldb.table.Table.openBlock(Table.java:137)
	at org.iq80.leveldb.table.Table.internalGet(Table.java:226)
	at org.iq80.leveldb.impl.TableCache.get(TableCache.java:101)
	at org.iq80.leveldb.impl.Level.get(Level.java:125)
	at org.iq80.leveldb.impl.Version.get(Version.java:144)
	at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:837)
	at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:806)
	at com.hivemc.chunker.conversion.encoding.bedrock.base.reader.BedrockColumnReader.readBlockEntities(BedrockColumnReader.java:231)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:20)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:8)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	... 2 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.nio.HeapByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocate(Unknown Source)
	at org.iq80.leveldb.util.ZLib.uncompress(ZLib.java:49)
	at org.iq80.leveldb.table.Table.readRawBlock(Table.java:202)
	at org.iq80.leveldb.table.Table.lambda$readBlock$1(Table.java:164)
	at org.iq80.leveldb.table.Table$$Lambda$416/0x0000000800236840.call(Unknown Source)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4903)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3574)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4898)
	at org.iq80.leveldb.util.LRUCache.load(LRUCache.java:56)
	at org.iq80.leveldb.table.Table.readBlock(Table.java:164)
	at org.iq80.leveldb.table.Table.openBlock(Table.java:137)
	at org.iq80.leveldb.table.Table.internalGet(Table.java:226)
	at org.iq80.leveldb.impl.TableCache.get(TableCache.java:101)
	at org.iq80.leveldb.impl.Level.get(Level.java:125)
	at org.iq80.leveldb.impl.Version.get(Version.java:144)
	at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:837)
	at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:806)
	at com.hivemc.chunker.conversion.encoding.bedrock.v1_17_30.reader.ColumnReader.readBiomeHeightMap(ColumnReader.java:26)
	at com.hivemc.chunker.conversion.encoding.bedrock.base.reader.BedrockColumnReader$$Lambda$591/0x000000080028f7f8.accept(Unknown Source)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:20)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:8)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor$$Lambda$361/0x00000008001afb40.run(Unknown Source)
```

**Comment by FormallyMyles** [comment]
The error you're seeing is because Chunker doesn't have enough memory to convert your world, this is usually because the world is quite big, or you don't have enough available memory (RAM). Chunker by default uses 75% of your available memory, so you might find that closing other applications before converting your world allows it to use the memory it needs.

You can also tell Chunker how much memory you want it to use, you need to run it from command-line in the form of `Chunker.exe -Xmx8G` to tell Chunker to use a maximum of 8 gigabytes of memory.

Alternatively, if your world is on Java edition you might find that using tools like MCASelector allow you to remove parts of your world that you haven't inhabited removing the requirement of needing more memory.

We can look further, but in most cases a large world does require more memory (especially with compression of the files), if you'd like us to we would need:
- The world size
- How much memory your computer has
- A copy of the world
