### ISSUE TITLE
java.lang.IllegalStateException: CURRENT file does not end with newline

### ISSUE THREAD

**Issue by Alee14** [HiveGamesOSS/Chunker#17]
### Chunker Version

cli-1.0.0

### Input World Version

Java 1.21.0

### Output World Version

Bedrock 1.21.0

### Platform / Operating System

Linux

### Issue Description

After entering the command, it had some issue with reading the world.

```
❯ java -jar chunker-cli-1.0.0.jar -i "world" -f JAVA_1_21_0 -o "world_JAVA"
Converting from Bedrock 1.21.0 to Java 1.21.0
0.00%
java.lang.IllegalStateException: CURRENT file does not end with newline
	at org.iq80.leveldb.impl.Filename.getCurrentFile(Filename.java:218)
	at org.iq80.leveldb.impl.VersionSet.recover(VersionSet.java:350)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:220)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:68)
	at com.hivemc.chunker.conversion.encoding.bedrock.base.reader.BedrockLevelReader.openDatabase(BedrockLevelReader.java:97)
	at com.hivemc.chunker.conversion.encoding.bedrock.base.reader.BedrockLevelReader.readLevel(BedrockLevelReader.java:115)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:20)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:8)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at java.base/java.lang.Thread.run(Thread.java:840)
Failed with exception
java.lang.IllegalStateException: CURRENT file does not end with newline
	at org.iq80.leveldb.impl.Filename.getCurrentFile(Filename.java:218)
	at org.iq80.leveldb.impl.VersionSet.recover(VersionSet.java:350)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:220)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:68)
	at com.hivemc.chunker.conversion.encoding.bedrock.base.reader.BedrockLevelReader.openDatabase(BedrockLevelReader.java:97)
	at com.hivemc.chunker.conversion.encoding.bedrock.base.reader.BedrockLevelReader.readLevel(BedrockLevelReader.java:115)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:20)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:8)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by Alee14** [comment]
Nevermind, got it solved

**Comment by minecraftchest1** [comment]
How did you solve it? I have the same issue.

**Comment by Alee14** [comment]
> How did you solve it? I have the same issue.

The issue I had was that it was a marketplace item, but I'm not allowed to tell you how to remove the "lock".

**Comment by minecraftchest1** [comment]
> > How did you solve it? I have the same issue.
> 
> The issue I had was that it was a marketplace item, but I'm not allowed to tell you how to remove the "lock".

That is complete BS.
