### ISSUE TITLE
java.io.IOException: Not enough disk space

### ISSUE THREAD

**Issue by DanyaLonyara** [HiveGamesOSS/Chunker#194]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

Java 1.21.0

### Output World Version

Bedrock 1.21.0

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `A fatal error occurred during conversion.`
Stack Trace: 
```
java.util.concurrent.CompletionException: org.iq80.leveldb.impl.DbImpl$BackgroundProcessingException: java.io.IOException: Недостаточно места на диске
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.Environment.cancel(Environment.java:85)
	at com.hivemc.chunker.conversion.WorldConverter.cancel(WorldConverter.java:609)
	at com.hivemc.chunker.conversion.WorldConverter.logFatalException(WorldConverter.java:441)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.handleException(TaskExecutor.java:109)
	at com.hivemc.chunker.scheduling.task.WrappedTask.lambda$setupFuture$0(WrappedTask.java:57)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:44)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.iq80.leveldb.impl.DbImpl$BackgroundProcessingException: java.io.IOException: Недостаточно места на диске
	at org.iq80.leveldb.impl.DbImpl.checkBackgroundException(DbImpl.java:550)
	at org.iq80.leveldb.impl.DbImpl.writeInternal(DbImpl.java:952)
	at org.iq80.leveldb.impl.DbImpl.put(DbImpl.java:875)
	at org.iq80.leveldb.impl.DbImpl.put(DbImpl.java:867)
	at com.hivemc.chunker.conversion.encoding.bedrock.v1_17_30.writer.ColumnWriter.writeHeightMapBiomes(ColumnWriter.java:108)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:20)
	at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:8)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	... 2 more
Caused by: java.io.IOException: Недостаточно места на диске
	at java.base/sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.truncate(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.mapInternal(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.map(Unknown Source)
	at org.iq80.leveldb.fileenv.MMWritableFile.openNewMap(MMWritableFile.java:87)
	at org.iq80.leveldb.fileenv.MMWritableFile.ensureCapacity(MMWritableFile.java:80)
	at org.iq80.leveldb.fileenv.MMWritableFile.append(MMWritableFile.java:56)
	at org.iq80.leveldb.fileenv.EnvImpl$DelegateWritableFile.append(EnvImpl.java:202)
	at org.iq80.leveldb.impl.LogWriter.writeChunk(LogWriter.java:171)
	at org.iq80.leveldb.impl.LogWriter.addRecord(LogWriter.java:150)
	at org.iq80.leveldb.impl.DbImpl.multipleWriteGroup(DbImpl.java:986)
	at org.iq80.leveldb.impl.DbImpl.writeInternal(DbImpl.java:927)
	... 11 more
```

**Comment by FormallyMyles** [comment]
The error would indicate that there is not enough disk space to complete the conversion. I would suggest freeing up some space before trying to convert, Chunker uses your temp directory to do this (which is usually on your C drive).
