### ISSUE TITLE
yu

### ISSUE THREAD

**Issue by Hacker979** [HiveGamesOSS/Chunker#206]
### Chunker Version

1.4.3-main-60b484e

### Input World Version

Java 1.21.0

### Output World Version

Bedrock 1.21.0

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `A fatal error occurred during conversion.`
Stack Trace: 
```
java.util.concurrent.CompletionException: java.io.IOException: Недостаточно места на диске
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.Environment.cancel(Environment.java:85)
	at com.hivemc.chunker.conversion.WorldConverter.cancel(WorldConverter.java:609)
	at com.hivemc.chunker.conversion.WorldConverter.logFatalException(WorldConverter.java:441)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.handleException(TaskExecutor.java:109)
	at com.hivemc.chunker.scheduling.task.WrappedTask.lambda$setupFuture$0(WrappedTask.java:57)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:44)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Недостаточно места на диске
	at java.base/sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.truncate(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.mapInternal(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.map(Unknown Source)
	at com.google.common.io.Files.mapInternal(Files.java:710)
	at com.google.common.io.Files.map(Files.java:697)
	at org.iq80.leveldb.fileenv.MMWritableFile.open(MMWritableFile.java:50)
	at org.iq80.leveldb.fileenv.EnvImpl.newWritableFile(EnvImpl.java:102)
	at org.iq80.leveldb.impl.Logs.createLogWriter(Logs.java:36)
	at org.iq80.leveldb.impl.VersionSet.logAndApply(VersionSet.java:287)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:280)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:68)
	at com.hivemc.chunker.conversion.encoding.bedrock.base.writer.BedrockLevelWriter.openDatabase(BedrockLevelWriter.java:101)
	at com.hivemc.chunker.conversion.encoding.bedrock.base.writer.BedrockLevelWriter.writeLevel(BedrockLevelWriter.java:227)
	at com.hivemc.chunker.scheduling.function.ThrowableFunction.invoke(ThrowableFunction.java:22)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	... 2 more
```

**Comment by FormallyMyles** [comment]
The error would indicate that there is not enough disk space to complete the conversion. I would suggest freeing up some space before trying to convert, Chunker uses your temp directory to do this (which is usually on your C drive).
