### ISSUE TITLE
try convert <Map of China> this map to Bedrock, `0833787b-4027-4dfd-a530-7451f7fadcb6`

### ISSUE THREAD

**Issue by 8MiYile** [HiveGamesOSS/Chunker#211]
### Chunker Version

1.4.3-main-60b484e

### Input World Version

Java 1.8.8

### Output World Version

Bedrock 1.21.40

### Platform / Operating System

linux-x64-6.6.59-amd64-desktop-hwe

### Issue Description

Error Displayed: `A fatal error occurred during conversion.`
Stack Trace: 
```
java.util.concurrent.CompletionException: java.util.zip.ZipException: invalid distance too far back
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.Environment.cancel(Environment.java:85)
	at com.hivemc.chunker.conversion.WorldConverter.cancel(WorldConverter.java:609)
	at com.hivemc.chunker.conversion.WorldConverter.logFatalException(WorldConverter.java:441)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.handleException(TaskExecutor.java:109)
	at com.hivemc.chunker.scheduling.task.WrappedTask.lambda$setupFuture$0(WrappedTask.java:57)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:44)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.zip.ZipException: invalid distance too far back
	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/java.io.DataInputStream.readFully(Unknown Source)
	at java.base/java.io.DataInputStream.readFully(Unknown Source)
	at com.hivemc.chunker.nbt.io.DataInputReaderBE.readBytes(DataInputReaderBE.java:25)
	at com.hivemc.chunker.nbt.tags.array.ByteArrayTag.decodeValue(ByteArrayTag.java:87)
	at com.hivemc.chunker.nbt.tags.collection.CompoundTag.decodeValue(CompoundTag.java:102)
	at com.hivemc.chunker.nbt.tags.collection.ListTag.decodeValue(ListTag.java:155)
	at com.hivemc.chunker.nbt.tags.collection.CompoundTag.decodeValue(CompoundTag.java:102)
	at com.hivemc.chunker.nbt.tags.collection.CompoundTag.decodeValue(CompoundTag.java:102)
	at com.hivemc.chunker.nbt.tags.Tag.decodeNamed(Tag.java:568)
	at com.hivemc.chunker.nbt.tags.Tag.readZLibJavaNBT(Tag.java:483)
	at com.hivemc.chunker.conversion.encoding.java.base.reader.util.MCAReader.decompressColumn(MCAReader.java:114)
	at com.hivemc.chunker.conversion.encoding.java.base.reader.util.MCAReader.lambda$readColumn$0(MCAReader.java:97)
	at com.hivemc.chunker.scheduling.function.ThrowableSupplier.invoke(ThrowableSupplier.java:20)
	at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
	at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
	at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
	... 2 more
```

**Comment by FormallyMyles** [comment]
The error would suggest that the map has malformed data which could be from an older version of Minecraft, unsure or modified with another tool? 

We can look into it further if you want to email the map to `chunker-public@hivemc.com`, but it is likely that the map is corrupt based on the error.
