### ISSUE TITLE
Out of memory error - CLI

### ISSUE THREAD

**Issue by Kusfo75** [HiveGamesOSS/Chunker#50]
### Chunker Version

chunker-cli-1.1.2.jar

### Input World Version

Java 1.20.1

### Output World Version

Bedrock 1.21.20

### Platform / Operating System

Windows 11

### Issue Description

When I convert the world, it crashes because of a memory heap error.

More data:
CPU > AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
RAM > 32 GB
Windows 11
Java World disk space > 5.38 GB

While crash:
- total ocupaid memory was around 14.4 GB (45% total memory)
- chunker process ocupaid memory was around 8 GB

Any idea?? Please, help! Thanks!

LOG:

...
73,72%
[1094.438s][warning][gc,alloc] Task Processor 7: Retried waiting for GCLocker too often allocating 1026 words
73,72%
73,72%
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:75)
        at java.base/java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:58)
        at com.hivemc.chunker.conversion.encoding.bedrock.base.writer.BedrockColumnWriter.writeBlockEntities(BedrockColumnWriter.java:316)
        at com.hivemc.chunker.conversion.encoding.bedrock.base.writer.BedrockColumnWriter$$Lambda$599/0x0000025b461ef460.accept(Unknown Source)
        at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:20)
        at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:8)
        at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
        at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
        at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
        at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
        at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
        at com.hivemc.chunker.scheduling.task.executor.TaskExecutor$$Lambda$403/0x0000025b4614adf8.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:842)
Failed with exception
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at com.hivemc.chunker.scheduling.task.Environment.cancel(Environment.java:85)
        at com.hivemc.chunker.conversion.WorldConverter.cancel(WorldConverter.java:609)
        at com.hivemc.chunker.conversion.WorldConverter.logFatalException(WorldConverter.java:441)
        at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.handleException(TaskExecutor.java:109)
        at com.hivemc.chunker.scheduling.task.WrappedTask.lambda$setupFuture$0(WrappedTask.java:57)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:44)
        at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
        at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:75)
        at java.base/java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:58)
        at com.hivemc.chunker.conversion.encoding.bedrock.base.writer.BedrockColumnWriter.writeBlockEntities(BedrockColumnWriter.java:316)
        at com.hivemc.chunker.conversion.encoding.bedrock.base.writer.BedrockColumnWriter$$Lambda$599/0x0000025b461ef460.accept(Unknown Source)
        at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:20)
        at com.hivemc.chunker.scheduling.function.ThrowableConsumer.invoke(ThrowableConsumer.java:8)
        at com.hivemc.chunker.scheduling.task.WrappedTask.apply(WrappedTask.java:84)
        at com.hivemc.chunker.scheduling.task.WrappedTask$WrappedTaskConstant.apply(WrappedTask.java:129)
        at com.hivemc.chunker.scheduling.task.WrappedTask.get(WrappedTask.java:77)
        at com.hivemc.chunker.scheduling.task.executor.TaskExecutorSupplier.run(TaskExecutorSupplier.java:42)
        at com.hivemc.chunker.scheduling.task.executor.TaskExecutor.threadLoop(TaskExecutor.java:178)
        at com.hivemc.chunker.scheduling.task.executor.TaskExecutor$$Lambda$403/0x0000025b4614adf8.run(Unknown Source)

**Comment by Kusfo75** [comment]
More info:
CPU > AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
RAM > 32 GB
Windows 11
Java World disk space > 5.38 GB

While crash:
- total ocupaid memory was around 14.4 GB (45% total memory)
- chunker process ocupaid memory was around 8 GB

**Comment by FormallyMyles** [comment]
As long as you're running without any memory arguments it should be trying to use all the memory, there is a chance windows is using the memory for other things.

You can explicitly boot Chunker with the `java -Xmx16G -jar chunker-cli.jar` parameter to limit/set the amount of memory it should use, there are also various other parameters like `-Xms8G` for initial memory usage.

If you want to reduce your memory usage (assuming you don't have another machine you could run this on), you can set up the pruning settings or use a GUI tool like MCASelector to remove unused chunks. Unfortunately memory usage varies world to world and Java compression can sometimes be really good leading to a lot of unpacking of data while Chunker is converting your world.

**Comment by FormallyMyles** [comment]
Closing this, if you need any more help let us know :)
